project:
  type: website
  output-dir: ../docs

website:
  title: "Grant Radar"
  description: "A digestible weekly view of NIH funding notices."
  site-url: https://muntasirmasum.github.io/grant-radar/
  repo-url: https://github.com/muntasirmasum/grant-radar
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - href: browse.qmd
        text: Browse
      - href: calendar.qmd
        text: Calendar
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    grid:
      body-width: 1200px
